// appekko-ui/src/app/features/register/components/register-form/register-form.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { EFirebaseAuthErrorCode } from 'src/app/core/constants/firebase';
import { PAGE_ROUTES_CONSTANTS } from 'src/app/core/constants/page-routes';
import { AuthService } from 'src/app/core/services/auth.service';

@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss']
})
export class RegisterFormComponent implements OnInit {

  PAGE_ROUTES_CONSTANTS = PAGE_ROUTES_CONSTANTS;

  hasError: boolean;
  errorMessage: string;

  form: FormGroup;

  @Output() beginningAuthentication: EventEmitter<null> = new EventEmitter();
  @Output() successfulAuthenticated: EventEmitter<null> = new EventEmitter();
  @Output() unSuccessfulAuthentication: EventEmitter<null> = new EventEmitter();

  constructor(private fb: FormBuilder, private auth: AuthService) {
    this.hasError = false;
    this.errorMessage = "";

    this.form = this.fb.group({
      fullName: new FormControl('', Validators.required),
      email: new FormControl('', [Validators.required]),
      password: new FormControl('', [
        Validators.required,
        Validators.pattern(/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/)
      ]),
    });
  }

  ngOnInit(): void {
  }

  async onFormSubmit(): Promise<void> {
    this.hasError = false;
    this.errorMessage = "";
    if (this.form.invalid) return;
    this.form.disable();
    this.beginningAuthentication.emit();

    const { fullName, email, password } = this.form.value;

    try {
      await this.auth.registerWithEmailAndPassword(fullName, email, password);
      this.successfulAuthenticated.emit();
    } catch (e) {
      this.hasError = true;
      this.errorMessage = this.getErrorMessage(e.code);
      this.unSuccessfulAuthentication.emit();
    }

    this.form.enable();
  }

  getErrorMessage(code: EFirebaseAuthErrorCode): string {
    switch (code) {
      case EFirebaseAuthErrorCode.EMAIL_ALREADY_EXISTS:
      case EFirebaseAuthErrorCode.EMAIL_ALREADY_IN_USE:
        return 'This email is already taken.';
      case EFirebaseAuthErrorCode.INVALID_EMAIL:
        return 'This email is invalid.';
      case EFirebaseAuthErrorCode.INVALID_PASSWORD:
        return 'This password is invalid.';
      case EFirebaseAuthErrorCode.WEAK_PASSWORD:
        return 'Password: 8+ characters, 1 number, 1 special character'
      default:
        return 'Something went wrong. Please try again.';
    }
  }

  get showFullNameError(): boolean {
    let control = this.form.controls['fullName'];
    return control.invalid;
  }

  get showEmailError(): boolean {
    let control = this.form.controls['email'];
    return control.invalid;
  }

  get showPasswordError(): boolean {
    let control = this.form.controls['password'];
    return control.invalid;
  }
}

<form (submit)="onFormSubmit()" [formGroup]="form" #myForm="ngForm">
    <div class="mb-4">
        <label htmlFor="fullName">Full Name</label>
        <input name="fullName" autofocus type="text" class="input-lg" formControlName="fullName" />
        <span class="hint danger" *ngIf="myForm.submitted && showFullNameError">Full name is required</span>
    </div>

    <div class="mb-4">
        <label htmlFor="email">Email</label>
        <input name="email" type="email" class="input-lg" formControlName="email" />
        <span class="hint danger" *ngIf="myForm.submitted && showEmailError">Email is required</span>
    </div>

    <div class="mb-5">
        <label htmlFor="password">Password</label>
        <input name="password" type="password" class="input-lg" formControlName="password" />
        <span class="hint" [ngClass]="{ 'danger': myForm.submitted && showPasswordError }">8+ characters, 1 number, 1 special character</span>
    </div>

    <div class="alert alert-danger mb-4" *ngIf="hasError">{{errorMessage}}</div>

    <button type="submit" [disabled]="form.disabled" class="btn btn-primary btn-lg btn-block mb-3">
        <span *ngIf="!form.disabled">Sign up</span>
        <span *ngIf="!!form.disabled">Signing up...</span>
    </button>

    <p class="mb-0">Already have an account?
        <a [routerLink]="['/' + PAGE_ROUTES_CONSTANTS.LOGIN]">Log in</a>
    </p>
</form>

// ui-web/src/shared/components/auth/register-form/register-form.tsx
import React, { useContext, useState } from 'react'
import { useForm } from 'react-hook-form';
import { Link, useHistory } from 'react-router-dom';
import { ROUTES } from '../../../../constants/routes';
import { FirebaseContext } from '../../../../context/firebase';
import { EFirebaseAuthErrorCode } from '../../../../core/enums/firebase';
import MainSpinner from '../../spinners/main-spinner';

type RegisterFormData = {
    fullName: string;
    email: string;
    password: string;
};

export default function RegisterForm() {
    const firebase = useContext(FirebaseContext);
    const history = useHistory();

    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    const { register, handleSubmit, errors, formState } = useForm<RegisterFormData>();
    const { isSubmitting } = formState;

    const onSubmit = handleSubmit(async (data: RegisterFormData, e: any) => {
        // Reset error message on form submit
        setErrorMessage(null);

        try {
            let res = await firebase.auth?.createUserWithEmailAndPassword(data.email, data.password);
            if (!res.user) throw Error("Something went wrong.");
            await res.user.updateProfile({ displayName: data.fullName });
            history.push(ROUTES.HOME);
        } catch (e) {
            setErrorMessage(getRegisterErrorMessage(e.code));
        }
    });

    function getRegisterErrorMessage(code: string): string {
        switch (code) {
            case EFirebaseAuthErrorCode.EMAIL_ALREADY_EXISTS:
            case EFirebaseAuthErrorCode.EMAIL_ALREADY_IN_USE:
                return 'This email is already taken.';
            case EFirebaseAuthErrorCode.INVALID_EMAIL:
                return 'This email is invalid.';
            case EFirebaseAuthErrorCode.INVALID_PASSWORD:
                return 'This password is invalid.';
            default:
                return 'Something went wrong. Please try again.';
        }
    }

    return (
        <div>
            <form onSubmit={onSubmit}>
                <div className="mb-4">
                    <label htmlFor="fullName">Full Name</label>
                    <input name="fullName" disabled={formState.isSubmitting} type="text" className="input-lg" ref={register({ required: true })} />
                    <span className="hint danger">{errors.fullName && "First name is required"}</span>
                </div>

                <div className="mb-4">
                    <label htmlFor="email">Email</label>
                    <input name="email" disabled={isSubmitting} type="email" className="input-lg" ref={register({ required: true, })} />
                    <span className="hint danger">{errors.email && " Required"}</span>
                </div>

                <div className="mb-5">
                    <label htmlFor="password">Password</label>
                    <input name="password" disabled={isSubmitting} type="password" className="input-lg" ref={register({ required: true, pattern: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/ })} />
                    <span className={`hint ${errors.password ? 'danger' : ''}`}>8+ characters, 1 number, 1 special character</span>
                </div>

                {errorMessage && <div className="alert alert-danger mb-4">{errorMessage}</div>}

                <button type="submit" disabled={isSubmitting} className="btn btn-primary btn-lg btn-block mb-3">
                    {!isSubmitting && 'Sign Up'}
                    {!!isSubmitting && <MainSpinner></MainSpinner>}
                </button>

                <p className="mb-0">Don't have an account? <Link to="login">Log in</Link></p>
            </form>
        </div>
    )
}
