// ui-web/src/shared/components/feed/feed-project/feed-project.tsx
import React from 'react'
import { IProject } from '../../../../core/models/project';
import Flag from '../../flag/flag';
import { EFlagSizes, EFlagTypes } from '../../../../core/enums/flags';
import { Link } from 'react-router-dom';
import FeedHeader from '../feed-event-header/feed-event-header';
import FeedProjectStats from './feed-project-stats/feed-project-stats';
import FeedEventContent from '../feed-event-content/feed-event-content';

export interface IProjectProps {
    project: IProject;
}

export default function FeedProject(props: IProjectProps) {
    const { project } = props;

    return (
        <div className="card">
            <div className="card-body">
                <FeedHeader author={project.owner} eventDate={project.startDate}></FeedHeader>

                <hr className="my-2" />

                <div className="d-flex align-items-center mb-3">
                    <span className="feed-event-title"><Link to="/">{project.name}</Link></span>
                    <div className="ml-3">
                        <Flag type={EFlagTypes.Project} size={EFlagSizes.Small}></Flag>
                    </div>
                </div>

                <div className="mb-4">
                    <FeedProjectStats project={project}></FeedProjectStats>
                </div>

                <FeedEventContent text={project.description}></FeedEventContent>
            </div>
        </div>
    )
}

// appekko-ui/src/app/features/feed/components/feed-list/feed-project/feed-project.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { EFlagSizes, EFlagTypes } from 'src/app/core/enums/flags';
import { IProject } from '../../../../../core/models/project.model';

@Component({
  selector: 'app-feed-project',
  templateUrl: './feed-project.component.html',
  styleUrls: ['./feed-project.component.scss']
})
export class FeedProjectComponent implements OnInit {

  @Input() project: IProject;

  EFlagTypes = EFlagTypes;
  EFlagSizes = EFlagSizes;

  constructor() { }

  ngOnInit(): void {
  }
}

<div class="card">
    <div class="card-body">
        <app-project-header [author]="project.author" [created]="project.created.toDate()"></app-project-header>

        <hr class="my-2" />

        <div class="d-flex align-items-center mb-3">
            <span class="feed-event-title"><a class="text-color" [routerLink]="">{{project.name}}</a></span>
            <div class="ml-3">
                <app-flag [type]="EFlagTypes.Project" [size]="EFlagSizes.Small"></app-flag>
            </div>
        </div>

        <div class="mb-4">
            <app-project-stats [category]="project.category" [technologies]="project.technologies" [repository]="project.repository"></app-project-stats>
        </div>

        <app-project-content [description]="project.description"></app-project-content>
    </div>
</div>
