// appekko-ui/src/app/features/login/components/login-form/login-form.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { EFirebaseAuthErrorCode } from 'src/app/core/constants/firebase';
import { PAGE_ROUTES_CONSTANTS } from 'src/app/core/constants/page-routes';
import { AuthService } from 'src/app/core/services/auth.service';

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.scss']
})
export class LoginFormComponent implements OnInit {

  PAGE_ROUTES_CONSTANTS = PAGE_ROUTES_CONSTANTS;

  hasError: boolean;
  errorMessage: string;

  form: FormGroup;

  @Output() beginningAuthentication: EventEmitter<null> = new EventEmitter();
  @Output() successfulAuthenticated: EventEmitter<null> = new EventEmitter();
  @Output() unSuccessfulAuthentication: EventEmitter<null> = new EventEmitter();

  constructor(private fb: FormBuilder, private auth: AuthService) {
    this.hasError = false;
    this.errorMessage = "";

    this.form = this.fb.group({
      email: new FormControl(''),
      password: new FormControl(''),
    });
  }

  ngOnInit(): void {
  }

  async onFormSubmit(): Promise<void> {
    this.hasError = false;
    this.errorMessage = "";
    if (this.form.invalid) return;
    this.form.disable();
    this.beginningAuthentication.emit();

    const { email, password } = this.form.value;

    try {
      await this.auth.signInWithEmailAndPassword(email, password);
      this.successfulAuthenticated.emit();
    } catch (e) {
      this.hasError = true;
      this.errorMessage = this.getErrorMessage(e.code);
      this.unSuccessfulAuthentication.emit();
    }

    this.form.enable();
  }

  getErrorMessage(code: EFirebaseAuthErrorCode): string {
    switch (code) {
      case EFirebaseAuthErrorCode.INVALID_EMAIL:
      case EFirebaseAuthErrorCode.INVALID_PASSWORD:
      case EFirebaseAuthErrorCode.WRONG_PASSWORD:
        return 'Incorrect email or password.';
      default:
        return 'Something went wrong. Please try again.';
    }
  }
}

<form (ngSubmit)="onFormSubmit()" [formGroup]="form">
    <div class="mb-4">
        <label htmlFor="email">Email</label>
        <input name="email" autofocus type="text" class="input-lg" formControlName="email" />
    </div>

    <div class="mb-5">
        <label htmlFor="password">Password</label>
        <input name="password" type="password" class="input-lg" formControlName="password" />
    </div>

    <div class="mb-4 alert alert-danger" *ngIf="!!hasError">{{ errorMessage }}</div>

    <button type="submit" [disabled]="form.disabled" class="btn btn-primary btn-lg btn-block mb-3">
        <span *ngIf="!form.disabled">Log in</span>
        <span *ngIf="!!form.disabled">Loggin in ...</span>
    </button>

    <p class="mb-0">Don't have an account? <a [routerLink]="['/' + PAGE_ROUTES_CONSTANTS.REGISTER]">Sign up</a></p>
</form>

// ui-web/src/shared/components/auth/login-form/login-form.tsx
import React, { useContext, useState } from 'react'
import { useForm } from 'react-hook-form';
import { Link, useHistory } from 'react-router-dom';
import { FirebaseContext } from '../../../../context/firebase';
import { ROUTES } from '../../../../constants/routes';
import MainSpinner from '../../spinners/main-spinner';
import { EFirebaseAuthErrorCode } from '../../../../core/enums/firebase';

type LoginFormData = {
    fullName: string;
    email: string;
    password: string;
};

export default function LoginForm() {
    const firebase = useContext(FirebaseContext);
    const history = useHistory();

    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    const { register, handleSubmit, formState } = useForm<LoginFormData>();
    const { isSubmitting } = formState;
    const onSubmit = (async (data: LoginFormData) => {
        setErrorMessage(null);
        try {
            await firebase.auth?.signInWithEmailAndPassword(data.email, data.password);
            history.push(ROUTES.HOME);
        } catch (e) {
            setErrorMessage(getErrorMessage(e.code));
        }
    });

    function getErrorMessage(code: EFirebaseAuthErrorCode): string {
        switch (code) {
            case EFirebaseAuthErrorCode.INVALID_EMAIL:
            case EFirebaseAuthErrorCode.INVALID_PASSWORD:
            case EFirebaseAuthErrorCode.WRONG_PASSWORD:
                return 'Incorrect email or password.';
            default:
                return 'Something went wrong. Please try again.';
        }
    }

    return (
        <div>
            <form onSubmit={handleSubmit(onSubmit)}>
                <div className="mb-4">
                    <label htmlFor="email">Email</label>
                    <input name="email" disabled={isSubmitting} type="text" className="input-lg" ref={register()} />
                </div>

                <div className="mb-5">
                    <label htmlFor="password">Password</label>
                    <input name="password" disabled={isSubmitting} type="password" className="input-lg" ref={register()} />
                </div>

                {!!errorMessage && <div className="mb-4 alert alert-danger">{errorMessage}</div>}

                <button type="submit" disabled={isSubmitting} className="btn btn-primary btn-lg btn-block mb-3">
                    {!isSubmitting && 'Log in'}
                    {!!isSubmitting && <MainSpinner></MainSpinner>}
                </button>

                <p className="mb-0">Don't have an account? <Link to="register">Sign up</Link></p>
            </form>
        </div>
    )
}
